/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.powens.sdk.model

import com.powens.sdk.model.AccessTokenType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An access token response with metadata.
 *
 * @param authToken Access token to use to authenticate calls to the data endpoints.
 * @param type 
 * @param userId 
 * @param expiresIn Duration in seconds of the token validity. If not specified, the token does not expire.
 */
@Serializable

data class AccessToken (

    /* Access token to use to authenticate calls to the data endpoints. */
    @SerialName(value = "auth_token") @Required val authToken: kotlin.String,

    @SerialName(value = "type") @Required val type: AccessTokenType,

    @SerialName(value = "id_user") @Required val userId: kotlin.ULong,

    /* Duration in seconds of the token validity. If not specified, the token does not expire. */
    @SerialName(value = "expires_in") val expiresIn: kotlin.Int? = null

) {


}

