/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.powens.sdk.model

import com.powens.sdk.model.AuthCodeAccess
import com.powens.sdk.model.AuthCodeType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An authorization code response with metadata.
 *
 * @param code The generated temporary code.
 * @param type 
 * @param access 
 * @param expiresIn The expiration delay of the code, in seconds.
 */
@Serializable

data class AuthCode (

    /* The generated temporary code. */
    @SerialName(value = "code") @Required val code: kotlin.String,

    @SerialName(value = "type") @Required val type: AuthCodeType,

    @SerialName(value = "access") @Required val access: AuthCodeAccess,

    /* The expiration delay of the code, in seconds. */
    @SerialName(value = "expires_in") val expiresIn: kotlin.Int? = null

) {


}

