/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.powens.sdk.model

import com.powens.sdk.model.BankAccountUsage

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A request to update metadata of a bank account.
 *
 * @param display Whether the bank account should be displayed and included in aggregated metrics.
 * @param name Display name of the account.
 * @param disabled Whether the bank account should be synchronized.
 * @param bookmarked Whether the bank account is bookmarked.
 * @param usage 
 */
@Serializable

data class BankAccountUpdateRequest (

    /* Whether the bank account should be displayed and included in aggregated metrics. */
    @SerialName(value = "display") val display: kotlin.Boolean? = null,

    /* Display name of the account. */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Whether the bank account should be synchronized. */
    @SerialName(value = "disabled") val disabled: kotlin.Boolean? = null,

    /* Whether the bank account is bookmarked. */
    @SerialName(value = "bookmarked") val bookmarked: kotlin.Boolean? = null,

    @SerialName(value = "usage") val usage: BankAccountUsage? = null

) {


}

