/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.powens.sdk.model


import kotlinx.serialization.*

/**
 * 
 *
 * Values: Connector,Sources,Accounts,AllAccounts
 */
@Serializable
enum class ConnectionExpandField(val value: kotlin.String) {

    @SerialName(value = "connector")
    Connector("connector"),

    @SerialName(value = "sources")
    Sources("sources"),

    @SerialName(value = "accounts")
    Accounts("accounts"),

    @SerialName(value = "all_accounts")
    AllAccounts("all_accounts");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ConnectionExpandField) "$data" else null

        /**
         * Returns a valid [ConnectionExpandField] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ConnectionExpandField? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

