/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.powens.sdk.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param clientId Client ID of the application.
 * @param clientSecret The client secret associated with the client ID.
 * @param code The temporary code that was delivered.
 * @param grantType The only accepted (and default) value is `authorization_code`.
 * @param redirectUri The exact `redirect_uri` that was specified during the initial OAuth2 step.
 */
@Serializable

data class ExchangeAccessTokenRequest (

    /* Client ID of the application. */
    @SerialName(value = "client_id") @Required val clientId: kotlin.String?,

    /* The client secret associated with the client ID. */
    @SerialName(value = "client_secret") @Required val clientSecret: kotlin.String?,

    /* The temporary code that was delivered. */
    @SerialName(value = "code") @Required val code: kotlin.String,

    /* The only accepted (and default) value is `authorization_code`. */
    @SerialName(value = "grant_type") val grantType: ExchangeAccessTokenRequest.GrantType? = null,

    /* The exact `redirect_uri` that was specified during the initial OAuth2 step. */
    @SerialName(value = "redirect_uri") val redirectUri: kotlin.String? = null

) {

    /**
     * The only accepted (and default) value is `authorization_code`.
     *
     * Values: AuthorizationCode
     */
    @Serializable
    enum class GrantType(val value: kotlin.String) {
        @SerialName(value = "authorization_code") AuthorizationCode("authorization_code");
    }

}

