/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.powens.sdk.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param token The generated service token.
 * @param tokenType The service token dedicated scope.
 */
@Serializable

data class ServiceAccessToken (

    /* The generated service token. */
    @SerialName(value = "token") val token: kotlin.String? = null,

    /* The service token dedicated scope. */
    @SerialName(value = "token_type") val tokenType: kotlin.String? = null

) {


}

