/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.powens.sdk.model

import com.powens.sdk.model.AccountSchemeName
import com.powens.sdk.model.TransactionCounterpartyType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Business or individual entity associated with a bank transaction.
 *
 * @param label Label/name of the counterparty.
 * @param accountSchemeName 
 * @param accountIdentification Account number of the counterparty.
 * @param type 
 */
@Serializable

data class TransactionCounterparty (

    /* Label/name of the counterparty. */
    @SerialName(value = "label") val label: kotlin.String? = null,

    @SerialName(value = "account_scheme_name") val accountSchemeName: AccountSchemeName? = null,

    /* Account number of the counterparty. */
    @SerialName(value = "account_identification") val accountIdentification: kotlin.String? = null,

    @SerialName(value = "type") val type: TransactionCounterpartyType? = null

) {


}

